FROM nginx:alpine
# Update Nginx config to listen on port 3000 instead of 80
RUN sed -i 's/listen       80;/listen       3000;/g' /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
EXPOSE 3000
